import { supabase } from '@/lib/supabase'
export type RequestForm = { serviceId?: string; professionalId?: string; categoryId: string; title: string; description: string; address: string; desiredDate?: string; desiredTime?: string; notes?: string }
export async function createRequest(input: RequestForm, files: File[]) { const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Faça login para solicitar um serviço.'); const { data, error } = await supabase.from('service_requests').insert({ client_id: user.id, service_id: input.serviceId || null, professional_id: input.professionalId || null, category_id: input.categoryId, title: input.title, description: input.description, address_text: input.address, desired_date: input.desiredDate ? new Date(`${input.desiredDate}T${input.desiredTime || '09:00'}`).toISOString() : null, desired_time: input.desiredTime || null, notes: input.notes || null, status: 'pending' }).select().single(); if (error) throw error; for (const file of files) { const path = `${user.id}/${data.id}/${crypto.randomUUID()}-${file.name}`; const { error: uploadError } = await supabase.storage.from('request-photos').upload(path, file); if (uploadError) throw uploadError; const { error: photoError } = await supabase.from('request_photos').insert({ request_id: data.id, storage_path: path }); if (photoError) throw photoError } return data }
export async function getClientRequests() { const { data, error } = await supabase.from('service_requests').select('id,title,description,status,desired_date,created_at,professional_id,quotes(id,amount,message,estimated_duration,status,professional_id,profiles:professional_id(full_name,avatar_url))').order('created_at', { ascending: false }); if (error) throw error; return data ?? [] }
export async function getProfessionalRequests() { const { data, error } = await supabase.from('service_requests').select('id,client_id,professional_id,title,description,address_text,desired_date,desired_time,notes,status,created_at,categories(name),profiles:client_id(full_name,phone),services(title,price_type,base_price),request_photos(id,storage_path)').in('status', ['pending', 'quoting']).order('created_at', { ascending: false }); if (error) throw error; return data ?? [] }
export async function submitQuote(requestId: string, amount: number, message: string, duration: string) { const { error } = await supabase.rpc('submit_quote', { p_request_id: requestId, p_amount: amount, p_message: message, p_duration: duration }); if (error) throw error }
export async function respondToDirectRequest(requestId: string, accept: boolean) { const { error } = await supabase.rpc('respond_to_direct_request', { p_request_id: requestId, p_accept: accept }); if (error) throw error }
export async function acceptQuote(quoteId: string, scheduledAt: string, address?: string) { const { error } = await supabase.rpc('accept_quote', { p_quote_id: quoteId, p_scheduled_at: new Date(scheduledAt).toISOString(), p_address: address || null }); if (error) throw error }
export async function getBookings() { const { data, error } = await supabase.from('bookings').select('id,status,scheduled_at,address_text,client_id,professional_id,services(title),profiles:client_id(full_name),quotes(service_request_id)').order('scheduled_at'); if (error) throw error; return data ?? [] }
export async function updateBookingStatus(id: string, status: 'in_progress' | 'completed' | 'cancelled') { const { error } = await supabase.rpc('update_booking_status', { p_booking_id: id, p_status: status }); if (error) throw error }
export async function createReview(bookingId: string, professionalId: string, rating: number, comment: string) { const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from('reviews').insert({ booking_id: bookingId, client_id: user?.id, professional_id: professionalId, rating, comment }); if (error) throw error }
export async function getMyAvailability() { const { data, error } = await supabase.from('availability').select('*').order('weekday'); if (error) throw error; return data ?? [] }
export async function saveAvailability(weekday: number, start: string, end: string) { const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from('availability').insert({ professional_id: user?.id, weekday, start_time: start, end_time: end, active: true }); if (error) throw error }
