import { supabase } from '@/lib/supabase'
import type { Availability, Category, Professional, Review, Service } from '@/types/database'
export type SearchFilters = { query?: string; category?: string; city?: string; maxPrice?: number; minRating?: number; page?: number; pageSize?: number }
type ServiceRow = Service & { categories: Category | null; professional_profiles: { bio: string | null; city: string | null; state: string | null; neighborhood: string | null; service_radius_km: number | null; latitude: number | null; longitude: number | null; average_rating: number; review_count: number; completed_services_count: number; profiles: { id: string; full_name: string; avatar_url: string | null } | null } | null }
export async function getCategories() { const { data, error } = await supabase.from('categories').select('id,name,slug,description,icon').eq('active', true).order('name'); if (error) throw error; return (data ?? []) as Category[] }
export async function searchProfessionals(filters: SearchFilters) {
  const pageSize = filters.pageSize ?? 9; const page = filters.page ?? 0
  let query = supabase.from('services').select('id,professional_id,category_id,title,description,base_price,price_type,active,categories(id,name,slug,description,icon),professional_profiles!inner(bio,city,state,neighborhood,service_radius_km,latitude,longitude,average_rating,review_count,completed_services_count,profiles!inner(id,full_name,avatar_url))', { count: 'exact' }).eq('active', true)
  if (filters.query?.trim()) query = query.or(`title.ilike.%${filters.query.trim()}%,description.ilike.%${filters.query.trim()}%`)
  if (filters.category) query = query.eq('category_id', filters.category)
  if (filters.city?.trim()) query = query.ilike('professional_profiles.city', `%${filters.city.trim()}%`)
  if (filters.maxPrice) query = query.lte('base_price', filters.maxPrice)
  if (filters.minRating) query = query.gte('professional_profiles.average_rating', filters.minRating)
  const { data, error, count } = await query.order('created_at', { ascending: false }).range(page * pageSize, page * pageSize + pageSize - 1)
  if (error) throw error
  const grouped = new Map<string, Professional>()
  for (const row of (data ?? []) as ServiceRow[]) { const details = row.professional_profiles; const identity = details?.profiles; if (!details || !identity) continue; const current = grouped.get(identity.id); const service: Service = { id: row.id, professional_id: row.professional_id, category_id: row.category_id, title: row.title, description: row.description, base_price: row.base_price, price_type: row.price_type, active: row.active }; if (current) { current.services.push(service); if (row.categories && !current.specialties.includes(row.categories.name)) current.specialties.push(row.categories.name) } else grouped.set(identity.id, { id: identity.id, fullName: identity.full_name, avatarUrl: identity.avatar_url, bio: details.bio, city: details.city, state: details.state, neighborhood: details.neighborhood, radiusKm: details.service_radius_km, latitude: details.latitude, longitude: details.longitude, averageRating: Number(details.average_rating), reviewCount: details.review_count, completedServicesCount: details.completed_services_count, specialties: row.categories ? [row.categories.name] : [], services: [service] }) }
  return { professionals: [...grouped.values()], count: count ?? 0, hasMore: (page + 1) * pageSize < (count ?? 0) }
}
export async function getProfessional(id: string) { const { data, error } = await supabase.from('professional_profiles').select('bio,city,state,neighborhood,service_radius_km,latitude,longitude,average_rating,review_count,completed_services_count,profiles!inner(id,full_name,avatar_url),services(id,professional_id,category_id,title,description,base_price,price_type,active,categories(name))').eq('user_id', id).single(); if (error) throw error; const profile = data as any; return { id: profile.profiles.id, fullName: profile.profiles.full_name, avatarUrl: profile.profiles.avatar_url, bio: profile.bio, city: profile.city, state: profile.state, neighborhood: profile.neighborhood, radiusKm: profile.service_radius_km, latitude: profile.latitude, longitude: profile.longitude, averageRating: Number(profile.average_rating), reviewCount: profile.review_count, completedServicesCount: profile.completed_services_count, specialties: [...new Set((profile.services ?? []).map((service: any) => service.categories?.name).filter(Boolean))], services: (profile.services ?? []).filter((service: Service) => service.active) } as Professional }
export async function getProfessionalReviews(id: string) { const { data, error } = await supabase.from('reviews').select('id,rating,comment,created_at,profiles!reviews_client_id_fkey(full_name)').eq('professional_id', id).order('created_at', { ascending: false }).limit(10); if (error) throw error; return (data ?? []).map((review: any) => ({ ...review, client: review.profiles })) as Review[] }
export async function getAvailability(id: string) { const { data, error } = await supabase.from('availability').select('id,weekday,start_time,end_time,active').eq('professional_id', id).eq('active', true).order('weekday'); if (error) throw error; return (data ?? []) as Availability[] }
export async function getGalleryUrls(id: string) { const { data, error } = await supabase.from('professional_photos').select('id,storage_path,caption,position').eq('professional_id', id).order('position'); if (error) throw error; return Promise.all((data ?? []).map(async (photo) => ({ ...photo, url: (await supabase.storage.from('professional-gallery').createSignedUrl(photo.storage_path, 3600)).data.signedUrl }))) }
