import { useEffect, useState } from 'react'
import { BarChart3, ShieldCheck, Users } from 'lucide-react'
import { DashboardLayout } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { getAdminMetrics, getAdminResources, getAdminUsers, moderate, setUserBlocked, type Metrics } from '@/lib/admin'
const labels: Record<string, string> = { users: 'Usuários cadastrados', professionals: 'Profissionais', clients: 'Clientes', services: 'Serviços cadastrados', requests: 'Solicitações', bookings: 'Agendamentos', completed: 'Serviços concluídos', gmv: 'GMV', average_ticket: 'Ticket médio' }
export function AdminMetricsPage() { const [metrics, setMetrics] = useState<Metrics | null>(null); useEffect(() => { getAdminMetrics().then(setMetrics).catch(() => setMetrics(null)) }, []); return <DashboardLayout><h1 className="text-2xl font-bold">Administração</h1><p className="mt-1 text-muted-foreground">Visão consolidada do marketplace.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics ? Object.entries(metrics).map(([key, value]) => <Card key={key}><CardContent className="p-5"><p className="text-2xl font-bold">{key === 'gmv' || key === 'average_ticket' ? `R$ ${Number(value).toFixed(2).replace('.', ',')}` : value}</p><p className="text-sm text-muted-foreground">{labels[key]}</p></CardContent></Card>) : <Card><CardContent className="p-5 text-muted-foreground">Carregando métricas...</CardContent></Card>}</div></DashboardLayout> }
export function AdminUsersPage({ role }: { role?: 'client' | 'professional' }) { const [users, setUsers] = useState<any[]>([]); const [message, setMessage] = useState(''); const load = () => getAdminUsers(role).then(setUsers); useEffect(load, [role]); const toggle = async (user: any) => { const reason = !user.is_blocked ? prompt('Motivo do bloqueio:') || undefined : undefined; try { await setUserBlocked(user.id, !user.is_blocked, reason); setMessage('Usuário atualizado.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível atualizar.') } }; return <DashboardLayout><h1 className="text-2xl font-bold">{role === 'client' ? 'Clientes' : role === 'professional' ? 'Profissionais' : 'Usuários'}</h1>{message && <p className="mt-3 text-sm text-primary">{message}</p>}<div className="mt-6 space-y-3">{users.map((user) => <Card key={user.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{user.full_name}</strong><p className="text-sm text-muted-foreground">{user.role} · {user.phone || 'Sem telefone'}</p>{user.is_blocked && <p className="text-xs text-red-600">Bloqueado: {user.blocked_reason || 'Sem motivo informado'}</p>}</div><Button size="sm" variant={user.is_blocked ? 'outline' : 'default'} onClick={() => toggle(user)}>{user.is_blocked ? 'Desbloquear' : 'Bloquear'}</Button></CardContent></Card>)}</div></DashboardLayout> }
export function AdminResourcePage({ resource }: { resource: 'categories' | 'services' | 'service_requests' | 'bookings' | 'reviews' }) { const [items, setItems] = useState<any[]>([]); const [message, setMessage] = useState(''); const load = () => getAdminResources(resource).then(setItems); useEffect(load, [resource]); const canModerate = resource === 'services' || resource === 'service_requests'; const act = async (id: string, status: 'approved' | 'rejected') => { try { await moderate(resource as 'services' | 'service_requests', id, status); setMessage('Conteúdo moderado.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível moderar.') } }; return <DashboardLayout><h1 className="text-2xl font-bold">{({ categories: 'Categorias', services: 'Serviços', service_requests: 'Solicitações', bookings: 'Agendamentos', reviews: 'Avaliações' } as Record<string,string>)[resource]}</h1>{message && <p className="mt-3 text-sm text-primary">{message}</p>}<div className="mt-6 space-y-3">{items.map((item) => <Card key={item.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{item.name || item.title || `Registro ${item.id.slice(0,8)}`}</strong><p className="mt-1 text-sm text-muted-foreground">{item.status || item.moderation_status || item.comment || 'Sem status'}</p></div>{canModerate && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => act(item.id, 'approved')}>Aprovar</Button><Button size="sm" variant="outline" onClick={() => act(item.id, 'rejected')}>Rejeitar</Button></div>}</CardContent></Card>)}</div></DashboardLayout> }
