import { useState, type FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { z } from 'zod'
import { Brand } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { dashboardFor, useAuth } from '@/contexts/auth-context'
import { isSupabaseConfigured, supabase } from '@/lib/supabase'
import type { UserRole } from '@/types/database'
function AuthFrame({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-slate-50 p-4"><div className="w-full max-w-md"><div className="mb-7 flex justify-center"><Brand /></div><Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card></div></main> }
function Notice({ message }: { message: string | null }) { return message ? <p className="mb-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{message}</p> : null }
export function LoginPage() { const nav = useNavigate(); const [error, setError] = useState<string | null>(null); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(null); const form = new FormData(event.currentTarget); const email = String(form.get('email')); const password = String(form.get('password')); const parsed = z.string().email().safeParse(email); if (!parsed.success || !password) return setError('Informe e-mail e senha válidos.'); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) return setError(error.message); const { data: { user } } = await supabase.auth.getUser(); const { data: nextProfile } = await supabase.from('profiles').select('role').eq('id', user?.id ?? '').maybeSingle(); nav(nextProfile ? dashboardFor(nextProfile.role as UserRole) : '/choose-role') }; return <AuthFrame title="Boas-vindas de volta" description="Entre para acessar sua conta."><form onSubmit={submit} className="space-y-4"><Notice message={!isSupabaseConfigured ? 'Configure as variáveis do Supabase para autenticar.' : error} /><div><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" className="mt-2" required /></div><div><Label htmlFor="password">Senha</Label><Input id="password" name="password" type="password" className="mt-2" required /></div><div className="text-right"><Link to="/forgot-password" className="text-sm text-primary hover:underline">Esqueci minha senha</Link></div><Button className="w-full" type="submit">Entrar</Button></form><p className="mt-5 text-center text-sm text-muted-foreground">Ainda não tem conta? <Link to="/signup" className="font-medium text-primary">Cadastre-se</Link></p></AuthFrame> }
export function SignupPage() { const nav = useNavigate(); const [params] = useSearchParams(); const [error, setError] = useState<string | null>(null); const preferred = params.get('role') === 'professional' ? 'professional' : 'client'; const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const fullName = String(form.get('fullName')).trim(); const email = String(form.get('email')); const password = String(form.get('password')); if (fullName.length < 3 || !z.string().email().safeParse(email).success || password.length < 8) return setError('Preencha nome, e-mail válido e uma senha com ao menos 8 caracteres.'); const { error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: fullName, role: form.get('role') } } }); if (error) return setError(error.message); nav('/choose-role?new=true') }; return <AuthFrame title="Crie sua conta" description="Comece gratuitamente em poucos minutos."><form onSubmit={submit} className="space-y-4"><Notice message={!isSupabaseConfigured ? 'Configure as variáveis do Supabase para autenticar.' : error} /><div><Label htmlFor="fullName">Nome completo</Label><Input id="fullName" name="fullName" className="mt-2" required /></div><div><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" className="mt-2" required /></div><div><Label htmlFor="password">Senha</Label><Input id="password" name="password" type="password" className="mt-2" required minLength={8} /></div><div><Label>Quero usar como</Label><div className="mt-2 grid grid-cols-2 gap-2"><label className="rounded-lg border p-3 text-sm"><input defaultChecked={preferred === 'client'} className="mr-2" type="radio" name="role" value="client" />Cliente</label><label className="rounded-lg border p-3 text-sm"><input defaultChecked={preferred === 'professional'} className="mr-2" type="radio" name="role" value="professional" />Profissional</label></div></div><Button className="w-full" type="submit">Criar conta</Button></form><p className="mt-5 text-center text-sm text-muted-foreground">Já possui conta? <Link to="/login" className="font-medium text-primary">Entrar</Link></p></AuthFrame> }
export function ForgotPasswordPage() { const [done, setDone] = useState(false); const [error, setError] = useState<string | null>(null); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const { error } = await supabase.auth.resetPasswordForEmail(String(new FormData(event.currentTarget).get('email')), { redirectTo: `${window.location.origin}/reset-password` }); if (error) setError(error.message); else setDone(true) }; return <AuthFrame title="Recuperar senha" description="Enviaremos um link para você criar uma nova senha.">{done ? <p className="rounded-lg bg-teal-50 p-4 text-sm text-teal-800">Se existir uma conta com este e-mail, você receberá as instruções em breve.</p> : <form onSubmit={submit} className="space-y-4"><Notice message={error} /><div><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" className="mt-2" required /></div><Button className="w-full">Enviar link</Button></form>}<Link to="/login" className="mt-5 block text-center text-sm text-primary">Voltar para entrar</Link></AuthFrame> }
export function ResetPasswordPage() { const nav = useNavigate(); const [error, setError] = useState<string | null>(null); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const password = String(new FormData(event.currentTarget).get('password')); if (password.length < 8) return setError('A senha precisa ter ao menos 8 caracteres.'); const { error } = await supabase.auth.updateUser({ password }); if (error) return setError(error.message); nav('/login') }; return <AuthFrame title="Definir nova senha" description="Escolha uma senha segura para sua conta."><form onSubmit={submit} className="space-y-4"><Notice message={error} /><div><Label htmlFor="password">Nova senha</Label><Input id="password" name="password" type="password" className="mt-2" minLength={8} required /></div><Button className="w-full">Atualizar senha</Button></form></AuthFrame> }
export function ChooseRolePage() { const nav = useNavigate(); const { profile, refreshProfile } = useAuth(); const [error, setError] = useState<string | null>(null); const setRole = async (role: UserRole) => { const { error } = await supabase.rpc('set_my_role', { new_role: role }); if (error) return setError(error.message); await refreshProfile(); nav(dashboardFor(role)) }; if (profile) return <AuthFrame title="Sua conta está pronta" description="Vamos para o seu painel."><Button className="w-full" onClick={() => nav(dashboardFor(profile.role))}>Ir para meu painel</Button></AuthFrame>; return <AuthFrame title="Como você quer usar a Pronto?" description="Você pode alterar suas preferências depois."><Notice message={error} /><div className="space-y-3"><Button className="h-auto w-full justify-start p-4 text-left" onClick={() => setRole('client')}><span><strong className="block">Quero contratar</strong><span className="font-normal opacity-80">Encontrar profissionais e solicitar serviços.</span></span></Button><Button variant="outline" className="h-auto w-full justify-start p-4 text-left" onClick={() => setRole('professional')}><span><strong className="block">Quero trabalhar</strong><span className="font-normal text-muted-foreground">Oferecer meus serviços e receber pedidos.</span></span></Button></div></AuthFrame> }
