import { CalendarClock, ClipboardList, Plus, Star, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { DashboardLayout } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { useAuth } from '@/contexts/auth-context'
function Stat({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <Card><CardContent className="flex items-center gap-4 p-5"><div className="rounded-lg bg-blue-100 p-2 text-primary"><Icon className="h-5 w-5" /></div><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card> }
export function ClientDashboard() { const { profile } = useAuth(); return <DashboardLayout><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Olá, {profile?.full_name?.split(' ')[0]}!</h1><p className="mt-1 text-muted-foreground">O que você precisa resolver hoje?</p></div><Button asChild><Link to="/client/requests"><Plus className="mr-2 h-4 w-4" />Novo pedido</Link></Button></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={ClipboardList} value="0" label="Pedidos ativos" /><Stat icon={CalendarClock} value="0" label="Agendamentos" /><Stat icon={Star} value="—" label="Avaliações feitas" /></div><Card className="mt-7"><CardHeader><CardTitle>Comece por aqui</CardTitle><CardDescription>Descreva o serviço que você precisa para receber propostas.</CardDescription></CardHeader><CardContent><Button asChild><Link to="/client/requests">Solicitar um serviço</Link></Button></CardContent></Card></DashboardLayout> }
export function ProfessionalDashboard() { const { profile } = useAuth(); return <DashboardLayout><div><h1 className="text-2xl font-bold">Olá, {profile?.full_name?.split(' ')[0]}!</h1><p className="mt-1 text-muted-foreground">Acompanhe sua operação e mantenha seu perfil pronto para novos clientes.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={ClipboardList} value="0" label="Novos pedidos" /><Stat icon={CalendarClock} value="0" label="Serviços agendados" /><Stat icon={Star} value="—" label="Sua avaliação" /></div><Card className="mt-7"><CardHeader><CardTitle>Seu perfil profissional</CardTitle><CardDescription>Cadastre seus serviços, área de atendimento e disponibilidade para começar a aparecer para clientes.</CardDescription></CardHeader><CardContent><Button asChild><Link to="/professional/services">Configurar serviços</Link></Button></CardContent></Card></DashboardLayout> }
export function AdminDashboard() { return <DashboardLayout><div><h1 className="text-2xl font-bold">Painel administrativo</h1><p className="mt-1 text-muted-foreground">Visão inicial da operação da plataforma.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={Users} value="—" label="Usuários cadastrados" /><Stat icon={ClipboardList} value="—" label="Pedidos abertos" /><Stat icon={CalendarClock} value="—" label="Reservas ativas" /></div><Card className="mt-7"><CardHeader><CardTitle>Base administrativa pronta</CardTitle><CardDescription>Esta área será expandida com moderação de perfis, categorias, serviços e indicadores.</CardDescription></CardHeader><CardContent><Button variant="outline" asChild><Link to="/admin/users">Gerenciar usuários</Link></Button></CardContent></Card></DashboardLayout> }
export function ComingSoon({ title }: { title: string }) { return <DashboardLayout><h1 className="text-2xl font-bold">{title}</h1><Card className="mt-6"><CardContent className="p-6 text-muted-foreground">Esta seção está preparada na estrutura do MVP e será implementada na próxima etapa.</CardContent></Card></DashboardLayout> }
