import { useEffect, useState, type FormEvent } from 'react'
import { DashboardLayout } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useAuth } from '@/contexts/auth-context'
import { supabase } from '@/lib/supabase'
import { getCategories } from '@/lib/marketplace'
export function ProfileSettingsPage() { const { profile, refreshProfile } = useAuth(); const [message, setMessage] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const { error } = await supabase.from('profiles').update({ full_name: String(f.get('name')), phone: String(f.get('phone')) || null }).eq('id', profile?.id); if (error) setMessage(error.message); else { await refreshProfile(); setMessage('Perfil atualizado.') } }; return <DashboardLayout><h1 className="text-2xl font-bold">Meu perfil</h1><Card className="mt-6 max-w-xl"><CardContent className="p-6"><form onSubmit={submit} className="space-y-4"><label><Label>Nome</Label><Input className="mt-2" name="name" defaultValue={profile?.full_name} required /></label><label><Label>Telefone</Label><Input className="mt-2" name="phone" defaultValue={profile?.phone || ''} /></label><Button>Salvar alterações</Button>{message && <p className="text-sm text-primary">{message}</p>}</form></CardContent></Card></DashboardLayout> }
export function ProfessionalSettingsPage() { const { profile } = useAuth(); const [categories, setCategories] = useState<any[]>([]); const [message, setMessage] = useState(''); useEffect(() => { getCategories().then(setCategories) }, []); const saveProfile = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const { error } = await supabase.from('professional_profiles').update({ bio: String(f.get('bio')), city: String(f.get('city')), state: String(f.get('state')), neighborhood: String(f.get('neighborhood')), service_radius_km: Number(f.get('radius')) || null }).eq('user_id', profile?.id); setMessage(error ? error.message : 'Perfil profissional atualizado.') }; const addService = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const { error } = await supabase.from('services').insert({ professional_id: profile?.id, category_id: String(f.get('category')), title: String(f.get('title')), description: String(f.get('description')) || null, price_type: String(f.get('priceType')), base_price: f.get('priceType') === 'fixed' ? Number(f.get('price')) : null }); setMessage(error ? error.message : 'Serviço cadastrado.'); event.currentTarget.reset() }; return <DashboardLayout><h1 className="text-2xl font-bold">Perfil e serviços</h1><p className="mt-1 text-muted-foreground">Configure sua apresentação, área de atendimento e catálogo.</p><div className="mt-6 grid max-w-3xl gap-5"><Card><CardContent className="p-6"><form onSubmit={saveProfile} className="space-y-3"><label><Label>Descrição profissional</Label><textarea className="mt-2 min-h-24 w-full rounded-lg border p-3" name="bio" /></label><div className="grid gap-3 sm:grid-cols-3"><Input name="city" placeholder="Cidade" /><Input name="state" placeholder="Estado" /><Input name="neighborhood" placeholder="Bairro" /></div><Input name="radius" type="number" placeholder="Raio de atendimento (km)" /><Button>Salvar perfil</Button></form></CardContent></Card><Card><CardContent className="p-6"><h2 className="font-semibold">Cadastrar serviço</h2><form onSubmit={addService} className="mt-4 space-y-3"><select name="category" required className="h-10 w-full rounded-lg border px-3"><option value="">Categoria</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><Input name="title" placeholder="Nome do serviço" required /><Input name="description" placeholder="Descrição" /><select name="priceType" className="h-10 w-full rounded-lg border px-3"><option value="quote">Sob orçamento</option><option value="fixed">Preço fixo</option></select><Input name="price" type="number" step="0.01" placeholder="Preço fixo (R$)" /><Button>Adicionar serviço</Button></form>{message && <p className="mt-3 text-sm text-primary">{message}</p>}</CardContent></Card></div></DashboardLayout> }
