import { Link, NavLink, useNavigate } from 'react-router-dom'
import { BriefcaseBusiness, LayoutDashboard, LogOut, Shield, UserRound } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/contexts/auth-context'
import { dashboardFor } from '@/contexts/auth-context'
export function Brand() { return <Link to="/" className="flex items-center gap-2 text-xl font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-primary text-primary-foreground">P</span>pronto</Link> }
export function Header() { const { profile, signOut } = useAuth(); const navigate = useNavigate(); const logout = async () => { await signOut(); navigate('/') }; return <header className="border-b bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><Brand /><nav className="flex items-center gap-2"><Link to="/categories" className="hidden text-sm text-muted-foreground sm:block">Explorar</Link>{profile ? <><Link to={dashboardFor(profile.role)} className="hidden text-sm text-muted-foreground sm:block">Meu painel</Link><Button variant="ghost" size="sm" onClick={logout}><LogOut className="mr-2 h-4 w-4" />Sair</Button></> : <><Button variant="ghost" size="sm" asChild><Link to="/login">Entrar</Link></Button><Button size="sm" asChild><Link to="/signup">Criar conta</Link></Button></>}</nav></div></header> }
const navByRole = { client: [{ to: '/client', icon: LayoutDashboard, label: 'Visão geral' }, { to: '/client/request/new', icon: BriefcaseBusiness, label: 'Solicitar serviço' }, { to: '/client/requests', icon: BriefcaseBusiness, label: 'Solicitações e orçamentos' }, { to: '/client/bookings', icon: BriefcaseBusiness, label: 'Agendamentos e histórico' }], professional: [{ to: '/professional', icon: LayoutDashboard, label: 'Visão geral' }, { to: '/professional/requests', icon: BriefcaseBusiness, label: 'Solicitações recebidas' }, { to: '/professional/bookings', icon: BriefcaseBusiness, label: 'Agendamentos e histórico' }, { to: '/professional/availability', icon: BriefcaseBusiness, label: 'Disponibilidade' }, { to: '/professional/services', icon: BriefcaseBusiness, label: 'Serviços e perfil' }], admin: [{ to: '/admin', icon: Shield, label: 'Métricas' }, { to: '/admin/users', icon: UserRound, label: 'Usuários' }, { to: '/admin/professionals', icon: UserRound, label: 'Profissionais' }, { to: '/admin/categories', icon: BriefcaseBusiness, label: 'Categorias' }, { to: '/admin/services', icon: BriefcaseBusiness, label: 'Serviços' }, { to: '/admin/requests', icon: BriefcaseBusiness, label: 'Solicitações' }, { to: '/admin/bookings', icon: BriefcaseBusiness, label: 'Agendamentos' }, { to: '/admin/reviews', icon: BriefcaseBusiness, label: 'Avaliações' }] }
export function DashboardLayout({ children }: { children: React.ReactNode }) { const { profile, signOut } = useAuth(); const navigate = useNavigate(); const items = navByRole[profile?.role ?? 'client']; return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Brand /><div className="flex items-center gap-3"><span className="hidden text-sm text-muted-foreground sm:block">{profile?.full_name}</span><Button variant="ghost" size="sm" onClick={() => signOut().then(() => navigate('/'))}><LogOut className="h-4 w-4" /></Button></div></div></header><div className="mx-auto flex max-w-7xl"><aside className="hidden w-56 shrink-0 border-r bg-white p-4 md:block"><p className="mb-4 px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Painel</p>{items.map(({ to, icon: Icon, label }) => <NavLink key={to} to={to} end className={({ isActive }) => `mb-1 flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium ${isActive ? 'bg-primary text-white' : 'text-slate-600 hover:bg-slate-100'}`}><Icon className="h-4 w-4" />{label}</NavLink>)}</aside><main className="min-w-0 flex-1 p-5 md:p-8">{children}</main></div></div> }
