import { useEffect, useMemo, useState, type ComponentType } from 'react'
import { MapPin, Search, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import type { Category, Professional } from '@/types/database'
export function SearchBar({ initialValue = '', onSearch }: { initialValue?: string; onSearch: (value: string) => void }) { const [value, setValue] = useState(initialValue); return <form onSubmit={(event) => { event.preventDefault(); onSearch(value) }} className="flex w-full gap-2"><Input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Ex.: eletricista, pintura, limpeza" aria-label="Buscar serviço" className="h-12 bg-white" /><Button className="h-12 shrink-0" type="submit"><Search className="mr-2 h-4 w-4" />Buscar</Button></form> }
export function CategoryChips({ categories, selected, onChange }: { categories: Category[]; selected?: string; onChange: (id?: string) => void }) { return <div className="flex gap-2 overflow-x-auto pb-2">{<Button size="sm" variant={!selected ? 'default' : 'outline'} onClick={() => onChange()}>Todas</Button>}{categories.map((category) => <Button key={category.id} size="sm" variant={selected === category.id ? 'default' : 'outline'} onClick={() => onChange(category.id)}>{category.name}</Button>)}</div> }
export function ProfessionalCard({ professional }: { professional: Professional }) { const address = [professional.neighborhood, professional.city, professional.state].filter(Boolean).join(', '); const startingPrice = professional.services.filter((service) => service.price_type === 'fixed' && service.base_price !== null).map((service) => Number(service.base_price)).sort((a, b) => a - b)[0]; return <Card className="overflow-hidden transition-shadow hover:shadow-md"><CardContent className="p-0"><div className="flex gap-4 p-5"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-full bg-blue-100 font-semibold text-primary">{professional.avatarUrl ? <img src={professional.avatarUrl} alt="" className="h-full w-full object-cover" /> : professional.fullName.slice(0, 1)}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold">{professional.fullName}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{professional.bio || 'Profissional disponível para atender sua região.'}</p></div><div className="flex shrink-0 items-center gap-1 text-sm font-medium"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />{professional.averageRating ? professional.averageRating.toFixed(1) : 'Novo'}</div></div><div className="mt-3 flex flex-wrap gap-1.5">{professional.specialties.slice(0, 3).map((specialty) => <span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600" key={specialty}>{specialty}</span>)}</div><div className="mt-4 flex items-end justify-between gap-3 text-sm"><span className="flex items-center gap-1 text-muted-foreground"><MapPin className="h-4 w-4" />{address || 'Localização a combinar'}</span><span className="shrink-0 font-medium">{startingPrice ? `A partir de R$ ${startingPrice.toFixed(2).replace('.', ',')}` : 'Sob orçamento'}</span></div></div></div><div className="border-t px-5 py-3"><Button variant="ghost" size="sm" asChild><Link to={`/professionals/${professional.id}`}>Ver perfil</Link></Button></div></CardContent></Card> }
export function ServicePrice({ type, price }: { type: 'fixed' | 'quote'; price: number | null }) { return type === 'quote' ? <span className="text-sm font-medium text-teal-700">Sob orçamento</span> : <span className="text-sm font-medium">R$ {Number(price ?? 0).toFixed(2).replace('.', ',')}</span> }
export function ServiceMap({ professionals }: { professionals: Professional[] }) { const mapped = useMemo(() => professionals.filter((professional) => professional.latitude && professional.longitude), [professionals]); const [Map, setMap] = useState<ComponentType | null>(null); useEffect(() => { import('react-leaflet').then((leaflet) => setMap(() => () => <leaflet.MapContainer center={mapped.length ? [mapped[0].latitude!, mapped[0].longitude!] : [-14.235, -51.9253]} zoom={mapped.length ? 12 : 4} scrollWheelZoom={false} className="h-64 w-full"><leaflet.TileLayer attribution="&copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a> contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{mapped.map((professional) => <leaflet.CircleMarker key={professional.id} center={[professional.latitude!, professional.longitude!]} radius={8} pathOptions={{ color: '#2563eb', fillColor: '#2563eb', fillOpacity: .8 }}><leaflet.Popup><strong>{professional.fullName}</strong><br />{professional.city}</leaflet.Popup></leaflet.CircleMarker>)}</leaflet.MapContainer>)) }, [mapped]); return <div className="overflow-hidden rounded-xl border bg-slate-100">{Map ? <Map /> : <div className="grid h-64 place-items-center text-sm text-muted-foreground">Carregando mapa...</div>}</div> }
